---

- name: Initialization docker swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_facts.tailscale0.ipv4.address }}"
  register: result_docker_swarm_manager_leader

- name: Create a docker overlay network
  community.docker.docker_network:
    name: nomad_overlay
    driver: overlay
    attachable: true
    enable_ipv6: false
    ipam_config:
      - subnet: 172.4.0.0/16
