---

- name: Install cni plugins
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz
    dest: /opt/cni/bin
    remote_src: true

- name: Transfert nomad certificats
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/vagrant/nomad/certs/
    mode: '0644'
  with_fileglob: "{{ playbook_dir }}/../secrets/nomad/{{ nomad_region }}/{{ nomad_datacenter }}/certs/*.pem"

- name: Generate nomad config
  ansible.builtin.template:
    src: templates/nomad-cluster-config.j2
    dest: /home/vagrant/nomad/config.hcl
