---

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository to apt
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    state: present

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Check if docker service has started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
